display:
  default:
    display_title: डीफॉल्ट
    display_options:
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
