display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        filename:
          label: नाम
        status:
          label: अवस्था
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      filters:
        status:
          expose:
            label: अवस्था
  page_2:
    display_options:
      fields:
        type:
          label: 'इकाई का प्रकार'
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
