display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        subject:
          separator: ', '
        uid:
          separator: ', '
        name:
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: कार्यवाही
        name_1:
          separator: ', '
      pager:
        options:
          tags:
            next: 'अगला >'
            previous: '‹ पिछले'
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      filters:
        langcode:
          expose:
            label: भाषा
  page_unapproved:
    display_options:
      fields:
        subject:
          separator: ', '
        uid:
          separator: ', '
        name:
          separator: ', '
        entity_id:
          separator: ', '
        changed:
          separator: ', '
        operations:
          label: कार्यवाही
        name_1:
          separator: ', '
      filters:
        langcode:
          expose:
            label: भाषा
