display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        status:
          label: अवस्था
        roles_target_id:
          label: भूमिका
        operations:
          label: कार्यवाही
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      filters:
        status:
          group_info:
            label: अवस्था
  page_1:
    display_title: पृष्ठ
