display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        bundle:
          label: प्रकार
        status:
          label: अवस्था
        operations:
          label: कार्यवाही
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      filters:
        bundle:
          expose:
            label: प्रकार
