display:
  default:
    display_title: डीफॉल्ट
    display_options:
      fields:
        status:
          label: अवस्था
          settings:
            format_custom_true: सक्रिय
        roles_target_id:
          label: भूमिका
        operations:
          label: कार्यवाही
        mail:
          separator: ', '
      pager:
        options:
          expose:
            items_per_page_label: 'विषय प्रति पृष्ठ'
            items_per_page_options_all_label: '-सभी-'
      exposed_form:
        options:
          reset_button_label: 'दोबारा से स्थापित करें|'
          exposed_sorts_label: 'क्रमबद्ध द्वारा'
          sort_desc_label: अवरोही
      filters:
        status:
          group_info:
            label: अवस्था
            group_items:
              1:
                title: सक्रिय
        roles_target_id:
          expose:
            label: भूमिका
        permission:
          expose:
            label: अनुमति
  page_1:
    display_title: पृष्ठ
