_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    hi: hi
    de: de
    ru: ru
    ar: ar
    '': null
  domains:
    en: testing.com
    hi: hi.testing.com
    de: de.testing.com
    ru: ru.testing.com
    ar: ar.testing.com
selected_langcode: site_default
