_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 59725e56-1854-4113-a07f-16f6686ff7de
name: "Employee's portfolio"
mail: vishaldemo28@gmail.com
slogan: 'get the Employees data here'
page:
  403: /node/558
  404: /node/557
  front: /node/64
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
